document.write( '  <div class=\"bottomcontact\">\n' );
document.write( '    <p class=\"bottomcontactp\">Contact</p>\n' );
document.write( '    <div class=\"wrapper4\">\n' );
document.write( '      <div class=\"\">\n' );
document.write( '        <p class=\"contactdetailsheading\">Phone</p>\n' );
document.write( '        <p class=\"contactdetails\">+90 212 284 35 37</p>\n' );
document.write( '      </div>\n' );
document.write( '      <div class=\"\">\n' );
document.write( '        <p class=\"contactdetailsheading\">Email</p>\n' );
document.write( '        <p class=\"contactdetails\">petstylist.istanbul@gmail.com</p>\n' );
document.write( '      </div>\n' );
document.write( '      <div class=\"\">\n' );
document.write( '        <p class=\"contactdetailsheading\">Hours of Operation</p>\n' );
document.write( '        <p class=\"contactdetails\">Mon - Sat: 9am - 6pm</p\n' );
document.write( '        <p class=\"contactdetails\">Sunday: Closed</p>\n' );
document.write( '      </div>\n' );
document.write( '      <div class=\"\">\n' );
document.write( '        <p class=\"contactdetailsheading\">Area of Service</p>\n' );
document.write( '        <p class=\"contactdetails\">1.levent Nispetiye mah.</p>\n' );
document.write( '        <p class=\"contactdetails\">Başa sok. No:7/B</p>\n' );
document.write( '        <p class=\"contactdetails\">Yeşilırmak apt, 34340</p>\n' );
document.write( '        <p class=\"contactdetails\">Beşiktaş/İstanbul</p>\n' );
document.write( '      </div>\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <img id=\"bottom\" class=\"aboutdoggie scrollbottom\" src=\"images/AboutDoggie.png\" alt=\"\">\n' );
document.write( '    <iframe class=\"map\" src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3007.723417990113!2d29.01814831578583!3d41.07503802326236!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab6402efa0ffd%3A0x6d9840aa3ddbee6e!2sPet%20Stylist!5e0!3m2!1str!2str!4v1575808693539!5m2!1str!2str\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\"></iframe>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '  </div>' );
