document.write( '<div class=\"div0\">\n' );
document.write( '      <div class=\"div1\">\n' );
document.write( '        <img class=\"logo\" src=\"images/logo.png\" alt=\"Logo\">\n' );
document.write( '        <a class=\"font1\" href=\"index.html\" target=\"_self\">Nurbanu Büyüktuna</a>\n' );
document.write( '      </div>\n' );
document.write( '\n' );
document.write( '      <div class=\"div2\">\n' );
document.write( '        <ul class=\"nav nav-justified\">\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\" href=\"index.html\">Home</a>\n' );
document.write( '          </li>\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\" href=\"aboutus.html\">About Us</a>\n' );
document.write( '          </li>\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\" href=\"single-coated-dogs.html\">Single Coated Dogs</a>\n' );
document.write( '          </li>\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\" href=\"double-coated-dogs.html\">Double Coated Dogs</a>\n' );
document.write( '          </li>\n' );
document.write( '          <li class=\"nav-item\">\n' );
document.write( '            <a class=\"nav-link\" href=\"care.html\">Care</a>\n' );
document.write( '          </li>\n' );
document.write( '          <li class=\"nav-item dropdown\">\n' );
document.write( '            <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">More</a>\n' );
document.write( '            <div class=\"dropdown-menu div3\">\n' );
document.write( '              <a class=\"dropdown-item menu font2\" href=\"eye-care.html\">Eye Care</a>\n' );
document.write( '              <a class=\"dropdown-item menu font2\" href=\"ear-care.html\">Ear Care</a>\n' );
document.write( '              <a class=\"dropdown-item menu font2\" href=\"dental-care.html\">Dental Care</a>\n' );
document.write( '              <a class=\"dropdown-item menu font2\" href=\"#bottom\">Contact</a>\n' );
document.write( '            </div>\n' );
document.write( '          </li>\n' );
document.write( '          <li>\n' );
document.write( '            <a class=\"btn btn-primary buttoncall\" href=\"tel:+902122843537\" role=\"button\">CALL +90 212 284 35 37</a>\n' );
document.write( '          </li>\n' );
document.write( '        </ul>\n' );
document.write( '      </div>\n' );
document.write( '        </div>' );
